import Head from 'next/head'
import { useState } from 'react';
import FAQ from '@/components/FAQ';
import Modal from '@/components/Modal';
import Header from '@/components/Header';
import HomeNews from '@/components/HomeNews';
import Contacts from '@/components/Contacts';
import HomeAbout from '@/components/HomeAbout';
import Advantages from '@/components/Advantages';
import TopProducts from '@/components/TopProducts';
import SortProducts from '@/components/SortProducts';
import HomeServices from '@/components/HomeServices';
import SliderProducts from '@/components/SliderProducts';
import AnimationChair from '@/components/AnimationChair';

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...locale
    },
  };
}

export default function Home(props) {

  const [showModal, setShowModal] = useState(false);

  function changeModal() {
    setShowModal(!showModal)
  }

  return (
    <>
      <Head>
        <title>KANZEC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='Home'>
        <Header />
        <SliderProducts />
        <TopProducts />
        <SortProducts />
        <AnimationChair />
        <Advantages />
        <HomeServices />
        <HomeNews />
        <HomeAbout />
        <FAQ />
        <Contacts changeModal={changeModal} />
        {showModal &&
          <Modal changeModal={changeModal} />
        }
      </div>
    </>
  )
}
